site_name: Belgium
theme:
  name: material
  features:
    - navigation.tracking
markdown_extensions:
  - pymdownx.snippets:
      base_path: docs
nav:
  - Home: index.md
  - Revenue: 
    - Breakdown: revenue/breakdown.md
    - Taxation policy: revenue/labour.md
    - Conclusion: revenue/conclusion.md
  - Expenditure: 
    - Breakdown: expenditure/breakdown.md
    - Social protection: expenditure/social_protection.md
    - General public services: expenditure/government.md
    - Education: expenditure/education.md
  - Fairness:
    - Wage distribution: fairness/wage_distribution.md
    - Buying a house: fairness/house.md
  - Populist claims:
    - Migration: claims/migration.md
    - Pension crisis: claims/pensions.md
    - Government waste: claims/government.md
